apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHJlY2R6a2dv
  CLOUDINARY_KEY: ODY2ODk2OTQ4ODg0MTg4
  CLOUDINARY_SECRET: aXkyalZkTlJPRUJGSnZocndIN1U1SFZGcmY0
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljbVZ1ZFdzaUxDSmhJam9pWTIxdWQzbHROSFl6TURCMU1qSnZjMmx6YjJ0NlpYcGhhaUo5LlJBQjd2OW5EX09iYTMybW9TQzJDY1E=
  DB_URL: bW9uZ29kYitzcnY6Ly9yZW51bGFwdG9wYmFja3VwX2RiX3VzZXI6ajZOemJyQUgzSEZUQ002bEBjbHVzdGVyMC5jcGN6eHp3Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
